export const tweets = [
  "\"Actions are but by intentions, and every person will get what he intended.\" — Prophet Muhammad ﷺ (Bukhari 1; Muslim 1907)",
  "\"The most beloved of deeds to Allah are those done regularly, even if small.\" — Prophet Muhammad ﷺ (Bukhari 6464; Muslim 783)",
  "\"Whoever believes in Allah and the Last Day should speak good or remain silent.\" — Prophet Muhammad ﷺ (Bukhari 6018; Muslim 47)",
  "\"Allah does not look at your bodies or your wealth, but He looks at your hearts and your deeds.\" — Prophet Muhammad ﷺ (Muslim 2564)",
  "\"None of you truly believes until he loves for his brother what he loves for himself.\" — Prophet Muhammad ﷺ (Bukhari 13; Muslim 45)",
  "\"The strong believer is better and more beloved to Allah than the weak believer.\" — Prophet Muhammad ﷺ (Muslim 2664)",
  "\"Whoever follows a path seeking knowledge, Allah makes easy for him a path to Paradise.\" — Prophet Muhammad ﷺ (Muslim 2699)",
  "\"Allah is Gentle and loves gentleness in all matters.\" — Prophet Muhammad ﷺ (Bukhari 6927; Muslim 2165)",
  "\"A good word is charity.\" — Prophet Muhammad ﷺ (Bukhari 2989; Muslim 1009)",
  "\"Your smiling in the face of your brother is charity.\" — Prophet Muhammad ﷺ (Tirmidhi 1956)",
  "\"The best among you are those with the best character.\" — Prophet Muhammad ﷺ (Bukhari 3559)",
  "\"Allah will not be merciful to those who are not merciful to mankind.\" — Prophet Muhammad ﷺ (Bukhari 7376; Muslim 2319)",
  "\"The merciful are shown mercy by Ar-Rahman. Be merciful on earth, and you will be shown mercy from above the heavens.\" — Prophet Muhammad ﷺ (Tirmidhi 1924)",
  "\"He who relieves a believer's hardship, Allah will relieve his hardship on the Day of Resurrection.\" — Prophet Muhammad ﷺ (Muslim 2699)",
  "\"He who conceals the faults of a Muslim, Allah will conceal his faults in this world and the Hereafter.\" — Prophet Muhammad ﷺ (Muslim 2699)",
  "\"Make things easy and do not make them difficult; give glad tidings and do not repel people.\" — Prophet Muhammad ﷺ (Bukhari 69; Muslim 1734)",
  "\"A believer is not stung twice from the same hole.\" — Prophet Muhammad ﷺ (Bukhari 6133; Muslim 2998)",
  "\"He who does not thank people has not thanked Allah.\" — Prophet Muhammad ﷺ (Abu Dawud 4811)",
  "\"Charity does not decrease wealth.\" — Prophet Muhammad ﷺ (Muslim 2588)",
  "\"No one humbles himself for the sake of Allah except that Allah raises his status.\" — Prophet Muhammad ﷺ (Muslim 2588)",
  "\"Part of the excellence of a person's Islam is his leaving what does not concern him.\" — Prophet Muhammad ﷺ (Tirmidhi 2317)",
  "\"The nearest of you to me on the Day of Judgment is the best of you in character.\" — Prophet Muhammad ﷺ (Tirmidhi 2018)",
  "\"The dua made between the adhan and the iqamah is not rejected.\" — Prophet Muhammad ﷺ (Tirmidhi 212)",
  "\"The nearest a servant comes to his Lord is when he is prostrating, so make much dua then.\" — Prophet Muhammad ﷺ (Muslim 482)",
  "\"Whoever sends salutations upon me once, Allah sends ten upon him.\" — Prophet Muhammad ﷺ (Muslim 408)",
  "\"Whoever says Subhan Allahi wa bihamdihi a hundred times a day will have all his sins forgiven.\" — Prophet Muhammad ﷺ (Bukhari 6405; Muslim 2691)",
  "\"Two phrases light on the tongue, heavy in the balance, beloved to the Most Merciful: Subhan Allahi wa bihamdihi, Subhan Allahil Azeem.\" — Prophet Muhammad ﷺ (Bukhari 6406; Muslim 2694)",
  "\"The best among you are those who learn the Qur'an and teach it.\" — Prophet Muhammad ﷺ (Bukhari 5027)",
  "\"Recite the Qur'an, for on the Day of Resurrection it will come as an intercessor for its companions.\" — Prophet Muhammad ﷺ (Muslim 804)",
  "\"Do not belittle any good deed, even meeting your brother with a cheerful face.\" — Prophet Muhammad ﷺ (Muslim 2626)",
  "\"When a man dies, his deeds end except three: ongoing charity, beneficial knowledge, or a righteous child who prays for him.\" — Prophet Muhammad ﷺ (Muslim 1631)",
  "\"The best charity is that given while you are healthy and hoping to live.\" — Prophet Muhammad ﷺ (Bukhari 1419; Muslim 1032)",
  "\"Tie it, and trust in Allah.\" — Prophet Muhammad ﷺ, asked whether to tie his camel or trust Allah and leave it loose (Tirmidhi 2517)",
  "\"Whoever believes in Allah and the Last Day should be generous to his guest.\" — Prophet Muhammad ﷺ (Bukhari 6019; Muslim 47)",
  "\"Whoever believes in Allah and the Last Day should maintain the bond of kinship.\" — Prophet Muhammad ﷺ (Bukhari 6138)",
  "\"The one who severs the bond of kinship will not enter Paradise.\" — Prophet Muhammad ﷺ (Bukhari 5984; Muslim 2556)",
  "\"Your mother, your mother, your mother, then your father.\" — Prophet Muhammad ﷺ, naming who deserves the best companionship (Bukhari 5971; Muslim 2548)",
  "\"The father is the middle gate to Paradise.\" — Prophet Muhammad ﷺ (Tirmidhi 1900)",
  "\"He is not a believer whose stomach is filled while his neighbor beside him goes hungry.\" — Prophet Muhammad ﷺ (Al-Adab al-Mufrad 112)",
  "\"He who does not show mercy to our young and does not respect the rights of our elders is not one of us.\" — Prophet Muhammad ﷺ (Abu Dawud 4943)",
  "\"I and the one who looks after an orphan will be together in Paradise like this,\" said the Prophet ﷺ, holding two fingers together. (Bukhari 5304)",
  "\"Charity is due on every joint of a person each day the sun rises.\" — Prophet Muhammad ﷺ (Bukhari 2989; Muslim 1009)",
  "\"Helping a man mount his animal, or lifting his belongings onto it, is charity.\" — Prophet Muhammad ﷺ (Bukhari 2989; Muslim 1009)",
  "\"Removing a harmful thing from the road is charity.\" — Prophet Muhammad ﷺ (Bukhari 2989; Muslim 1009)",
  "\"The strong is not the one who overcomes people by his strength, but the one who controls himself when angry.\" — Prophet Muhammad ﷺ (Bukhari 6114; Muslim 2609)",
  "\"Do not become angry.\" — Prophet Muhammad ﷺ, when asked to give advice (Bukhari 6116)",
  "\"Whoever suppresses his anger while able to act on it, Allah will call him on the Day of Resurrection to choose whichever heavenly maiden he wishes.\" — Prophet Muhammad ﷺ (Tirmidhi 2021)",
  "\"Modesty is a branch of faith.\" — Prophet Muhammad ﷺ (Bukhari 9; Muslim 35)",
  "\"Faith has over seventy branches, the most excellent of which is the declaration that there is no god but Allah.\" — Prophet Muhammad ﷺ (Muslim 35)",
  "\"The most humble branch of faith is removing what is harmful from the path.\" — Prophet Muhammad ﷺ (Muslim 35)",
  "\"He who has an atom's weight of pride in his heart will not enter Paradise.\" — Prophet Muhammad ﷺ (Muslim 91)",
  "\"Allah is Beautiful and He loves beauty.\" — Prophet Muhammad ﷺ (Muslim 91)",
  "\"Purity is half of faith.\" — Prophet Muhammad ﷺ (Muslim 223)",
  "\"Prayer is light.\" — Prophet Muhammad ﷺ (Muslim 223)",
  "\"Patience is illumination.\" — Prophet Muhammad ﷺ (Muslim 223)",
  "\"The Qur'an is a proof for you or against you.\" — Prophet Muhammad ﷺ (Muslim 223)",
  "\"Women and perfume have been made dear to me, and the comfort of my eyes has been placed in prayer.\" — Prophet Muhammad ﷺ (Nasa'i 3940)",
  "\"The first deed for which a servant will be brought to account on the Day of Resurrection is his prayer.\" — Prophet Muhammad ﷺ (Tirmidhi 413)",
  "\"Pray as you have seen me praying.\" — Prophet Muhammad ﷺ (Bukhari 631)",
  "\"Whoever builds a mosque for Allah's sake, Allah will build for him the like of it in Paradise.\" — Prophet Muhammad ﷺ (Bukhari 450; Muslim 533)",
  "\"Prayer in congregation is twenty-seven times superior to prayer offered alone.\" — Prophet Muhammad ﷺ (Bukhari 645; Muslim 650)",
  "\"The five daily prayers are an expiation for the sins committed between them, so long as one avoids the major sins.\" — Prophet Muhammad ﷺ (Muslim 233)",
  "\"Whoever prays Fajr is under the protection of Allah.\" — Prophet Muhammad ﷺ (Muslim 657)",
  "\"The most excellent prayer after the prescribed prayers is prayer in the middle of the night.\" — Prophet Muhammad ﷺ (Muslim 1163)",
  "\"Our Lord descends every night to the lowest heaven when the last third of the night remains, saying: Who calls upon Me, that I may answer him?\" — Prophet Muhammad ﷺ (Bukhari 1145; Muslim 758)",
  "\"Whoever fasts Ramadan out of faith and hope of reward, his past sins will be forgiven.\" — Prophet Muhammad ﷺ (Bukhari 38; Muslim 760)",
  "\"Whoever prays at night in Ramadan out of faith and hope of reward, his past sins will be forgiven.\" — Prophet Muhammad ﷺ (Bukhari 37; Muslim 759)",
  "\"Whoever fasts Ramadan and follows it with six days of Shawwal, it is as if he fasted the whole year.\" — Prophet Muhammad ﷺ (Muslim 1164)",
  "\"Fasting is a shield.\" — Prophet Muhammad ﷺ (Bukhari 1904; Muslim 1151)",
  "\"The unpleasant smell from the mouth of a fasting person is more beloved to Allah than the scent of musk.\" — Prophet Muhammad ﷺ (Bukhari 1894; Muslim 1151)",
  "\"Allah has made Zakah obligatory on them, to be taken from the wealthy among them and given to the poor.\" — Prophet Muhammad ﷺ, instructing Mu'adh in Yemen (Bukhari 1395)",
  "\"Save yourself from the Fire even by giving half a date-fruit in charity.\" — Prophet Muhammad ﷺ (Bukhari 1417; Muslim 1016)",
  "\"Sawm is a shield, and charity extinguishes sin as water extinguishes fire.\" — Prophet Muhammad ﷺ (Tirmidhi 614)",
  "\"The upper hand is better than the lower hand.\" — Prophet Muhammad ﷺ (Bukhari 1429; Muslim 1033)",
  "\"Whoever gives iftar to a fasting person will have a reward like his.\" — Prophet Muhammad ﷺ (Tirmidhi 807)",
  "\"Truthfulness leads to righteousness, and righteousness leads to Paradise.\" — Prophet Muhammad ﷺ (Bukhari 6094; Muslim 2607)",
  "\"Falsehood leads to wickedness, and wickedness leads to the Fire.\" — Prophet Muhammad ﷺ (Bukhari 6094; Muslim 2607)",
  "\"The signs of a hypocrite are three: when he speaks he lies, when he promises he breaks it, when trusted he betrays.\" — Prophet Muhammad ﷺ (Bukhari 33; Muslim 59)",
  "\"Whoever can guarantee what is between his jaws and what is between his legs, I guarantee him Paradise.\" — Prophet Muhammad ﷺ (Bukhari 6474)",
  "\"The Muslim is one from whose tongue and hand other Muslims are safe.\" — Prophet Muhammad ﷺ (Bukhari 10; Muslim 40)",
  "\"The believer is not a slanderer, nor does he curse others, nor is he obscene or shameless.\" — Prophet Muhammad ﷺ (Tirmidhi 1977)",
  "\"Do not envy one another, do not hate one another; be, O servants of Allah, brothers.\" — Prophet Muhammad ﷺ (Muslim 2563)",
  "\"No one forgives except that Allah increases him in honor.\" — Prophet Muhammad ﷺ (Muslim 2588)",
  "\"Whoever believes in Allah and the Last Day should not harm his neighbor.\" — Prophet Muhammad ﷺ (Bukhari 6018; Muslim 47)",
  "\"Jibril kept advising me about the neighbor until I thought he would tell me to make him an heir.\" — Prophet Muhammad ﷺ (Bukhari 6014; Muslim 2624)",
  "\"O people, spread the salam, feed others, and pray at night while people are asleep; you will enter Paradise in peace.\" — Prophet Muhammad ﷺ (Tirmidhi 2485)",
  "\"Shall I tell you of something that will make you love one another? Spread salam among yourselves.\" — Prophet Muhammad ﷺ (Muslim 54)",
  "\"You will not enter Paradise until you believe, and you will not believe until you love one another.\" — Prophet Muhammad ﷺ (Muslim 54)",
  "\"Whoever guides someone to good will have a reward like the one who did it.\" — Prophet Muhammad ﷺ (Muslim 1893)",
  "\"Convey from me, even if it is one verse.\" — Prophet Muhammad ﷺ (Bukhari 3461)",
  "\"The religion is sincere advice — to Allah, His Book, His Messenger, the leaders of the Muslims, and the common folk.\" — Prophet Muhammad ﷺ (Muslim 55)",
  "\"The religion is easy, and whoever overburdens himself in it will be overwhelmed.\" — Prophet Muhammad ﷺ (Bukhari 39)",
  "\"Do not take on more than you can bear; the deeds most beloved to Allah are those done most consistently.\" — Prophet Muhammad ﷺ (Bukhari 6465; Muslim 782)",
  "\"If Allah wants to do good to somebody, He afflicts him with trials.\" — Prophet Muhammad ﷺ (Bukhari 5645)",
  "\"The one who repents from sin is like one who has no sin.\" — Prophet Muhammad ﷺ (Ibn Majah 4250)",
  "\"Allah is more pleased with the repentance of His servant than one of you would be with finding his lost camel in the desert.\" — Prophet Muhammad ﷺ (Muslim 2747)",
  "\"Every son of Adam sins, and the best of sinners are those who repent.\" — Prophet Muhammad ﷺ (Tirmidhi 2499)",
  "\"Be in this world as if you were a stranger, or a traveler.\" — Prophet Muhammad ﷺ (Bukhari 6416)",
  "\"Remember often the destroyer of pleasures — death.\" — Prophet Muhammad ﷺ (Tirmidhi 2307)",
  "\"There is nothing more honorable to Allah than supplication.\" — Prophet Muhammad ﷺ (Tirmidhi 3370)",
  "\"If you relied upon Allah with true reliance, He would provide for you as He provides the birds: they go out hungry and return full.\" — Prophet Muhammad ﷺ (Tirmidhi 2344)",
  "\"Wondrous is the affair of the believer: if good happens to him, he is grateful; if harm befalls him, he is patient — and both are good for him.\" — Prophet Muhammad ﷺ (Muslim 2999)",
  "\"No fatigue, disease, sorrow, sadness, hurt, or distress befalls a Muslim, even the prick of a thorn, but Allah expiates some of his sins for it.\" — Prophet Muhammad ﷺ (Bukhari 5641; Muslim 2573)",
  "\"The example of a good companion and a bad one is that of a perfume seller and a blacksmith: one gives a pleasant scent, the other burns you or smells foul.\" — Prophet Muhammad ﷺ (Bukhari 2101; Muslim 2628)",
  "\"Whoever kills a person who has a treaty with the Muslims will not smell the fragrance of Paradise, though its fragrance is found for a journey of forty years.\" — Prophet Muhammad ﷺ (Bukhari 3166)",
  "\"The best of you is the best to his wives, and I am the best of you to my wives.\" — Prophet Muhammad ﷺ (Tirmidhi 3895)",
  "\"A man saw a dog eating mud out of thirst, so he filled his shoe with water and gave it to drink. Allah thanked him for that and forgave him.\" — Prophet Muhammad ﷺ (Bukhari 2466; Muslim 2244)",
  "\"He who lets people hear of his good deeds to win their praise, Allah will let people know his real intention; and he who shows off, Allah will expose him.\" — Prophet Muhammad ﷺ (Bukhari 6499; Muslim 2986)",
  "\"Do you know what backbiting is? It is saying something about your brother that he would dislike.\" — Prophet Muhammad ﷺ (Muslim 2589)",
  "\"A tale-carrier will not enter Paradise.\" — Prophet Muhammad ﷺ (Bukhari 6056; Muslim 105)",
  "\"The seller and buyer may annul a sale before parting; if both spoke the truth, they are blessed; if they lied or hid defects, the blessing is erased.\" — Prophet Muhammad ﷺ (Bukhari 2079; Muslim 1532)",
  "\"The truthful, trustworthy merchant will be with the Prophets, the truthful, and the martyrs.\" — Prophet Muhammad ﷺ (Tirmidhi 1209)",
  "\"Nobody has ever eaten a better meal than that which he has earned by working with his own hands.\" — Prophet Muhammad ﷺ (Bukhari 2072)",
  "\"Whoever takes the wealth of people intending to repay it, Allah will repay it on his behalf; whoever takes it intending to destroy it, Allah will destroy him.\" — Prophet Muhammad ﷺ (Bukhari 2387)",
  "\"When a Muslim visits his sick brother, he is harvesting the fruits of Paradise until he returns.\" — Prophet Muhammad ﷺ (Muslim 2568)",
  "\"No one will enter Paradise by his deeds alone. They said: Not even you? He said: Not even me, unless Allah covers me with His mercy.\" — Prophet Muhammad ﷺ (Bukhari 5673; Muslim 2816)",
  "\"There is a gate in Paradise called Ar-Rayyan, through which none will enter except those who fasted.\" — Prophet Muhammad ﷺ (Bukhari 1896; Muslim 1152)",
  "\"There is a tree in Paradise so vast that a rider could travel in its shade for a hundred years without crossing it.\" — Prophet Muhammad ﷺ (Bukhari 3251; Muslim 2826)",
  "\"Your fire, which the son of Adam kindles, is one part of seventy parts of the Fire of Hell.\" — Prophet Muhammad ﷺ (Bukhari 3265; Muslim 2843)",
  "\"The example of the one who remembers his Lord and the one who does not is like the example of the living and the dead.\" — Prophet Muhammad ﷺ (Bukhari 6407)",
  "\"The believers, in their mutual mercy, love, and compassion, are like one body: if one part suffers, the whole body responds with fever and sleeplessness.\" — Prophet Muhammad ﷺ (Bukhari 6011; Muslim 2586)",
  "\"There are two blessings which many people lose: health and free time.\" — Prophet Muhammad ﷺ (Bukhari 6412)",
  "\"The world is a prison for the believer and a paradise for the disbeliever.\" — Prophet Muhammad ﷺ (Muslim 2956)",
  "\"Give the road its rights: lowering the gaze, refraining from harm, returning greetings, and enjoining good and forbidding evil.\" — Prophet Muhammad ﷺ (Bukhari 2465; Muslim 2121)",
  "\"Let him be humbled, let him be humbled: he who finds his parents, one or both, in old age, and does not enter Paradise through serving them.\" — Prophet Muhammad ﷺ (Muslim 2551)",
  "\"A man who gives charity so secretly his left hand does not know what his right has given — he will be shaded by Allah on the Day with no shade but His.\" — Prophet Muhammad ﷺ (Bukhari 660; Muslim 1031)",
  "\"Fear Allah, and be just among your children.\" — Prophet Muhammad ﷺ, when told a father had given one son a gift but not the others (Bukhari 2587; Muslim 1623)",
  "\"If Allah wants good for a person, He gives him understanding of the religion.\" — Prophet Muhammad ﷺ (Bukhari 71; Muslim 1037)",
  "\"Your servants are your brothers whom Allah has placed under your authority; feed them from what you eat and clothe them from what you wear.\" — Prophet Muhammad ﷺ (Bukhari 30; Muslim 1661)",
  "\"May Allah show mercy to a man who is lenient when he buys, when he sells, and when he demands repayment.\" — Prophet Muhammad ﷺ (Bukhari 2076)",
  "\"None of you truly believes until I am more beloved to him than his father, his children, and all of mankind.\" — Prophet Muhammad ﷺ (Bukhari 15; Muslim 44)",
  "\"Prayer at its proper time; then kindness to parents; then jihad in the way of Allah.\" — Prophet Muhammad ﷺ, naming the deeds most loved by Allah (Bukhari 527; Muslim 85)",
  "\"Look at those below you in worldly things, not at those above you, for that is more fitting so you do not belittle Allah's blessing upon you.\" — Prophet Muhammad ﷺ (Bukhari 6490; Muslim 2963)",
  "\"Richness is not in having abundant possessions; rather, true richness is the richness of the soul.\" — Prophet Muhammad ﷺ (Bukhari 6446; Muslim 1051)",
  "\"Allah is more merciful to His servants than a mother is to her child.\" — Prophet Muhammad ﷺ (Bukhari 5999; Muslim 2754)",
  "\"When Allah decreed the creation, He wrote in His Book, which is with Him above the Throne: My mercy prevails over My wrath.\" — Prophet Muhammad ﷺ (Bukhari 7404; Muslim 2751)",
  "\"Allah has ninety-nine names, one hundred less one; whoever enumerates them will enter Paradise.\" — Prophet Muhammad ﷺ (Bukhari 6410; Muslim 2677)",
  "\"None of you should wish for death because of a calamity that befalls him; but if he must, let him say: O Allah, keep me alive while life is better for me.\" — Prophet Muhammad ﷺ (Bukhari 5671; Muslim 2680)",
  "\"Allah has enjoined excellence in all things. When you slaughter, slaughter well: let each of you sharpen his blade and spare suffering to the animal.\" — Prophet Muhammad ﷺ (Muslim 1955)",
  "\"Fear Allah wherever you are, follow a bad deed with a good one to erase it, and treat people with good character.\" — Prophet Muhammad ﷺ (Tirmidhi 1987)",
  "\"Those who are just will be with Allah upon pulpits of light: those who are just in their rule, with their families, and in all that is entrusted to them.\" — Prophet Muhammad ﷺ (Muslim 1827)",
  "\"Whoever remains silent is saved.\" — Prophet Muhammad ﷺ (Tirmidhi 2501)",
  "\"The believer who mixes with people and bears their harm with patience has a greater reward than one who does not mix with people and does not bear their harm.\" — Prophet Muhammad ﷺ (Tirmidhi 2507; Ibn Majah 4032)",
  "\"Beware the supplication of the oppressed, for there is no barrier between it and Allah.\" — Prophet Muhammad ﷺ, instructing Mu'adh in Yemen (Bukhari 1496)",
  "\"Help your brother, whether he is an oppressor or is oppressed — by preventing him from oppressing, in the case of the oppressor.\" — Prophet Muhammad ﷺ (Bukhari 2444)",
  "\"Whoever loves for Allah's sake, hates for Allah's sake, gives for Allah's sake, and withholds for Allah's sake, has perfected his faith.\" — Prophet Muhammad ﷺ (Abu Dawud 4681)",
  "\"Every religion has a distinct characteristic, and the distinct characteristic of Islam is modesty.\" — Prophet Muhammad ﷺ (Ibn Majah 4181)",
  "\"Part of glorifying Allah is honoring a gray-haired Muslim.\" — Prophet Muhammad ﷺ (Abu Dawud 4843)",
  "\"A woman entered the Fire because of a cat she had tied up, neither feeding it nor releasing it to eat from the vermin of the earth.\" — Prophet Muhammad ﷺ (Bukhari 3318; Muslim 2242)",
  "\"The believer's soul remains suspended by his debt until it is settled for him.\" — Prophet Muhammad ﷺ (Tirmidhi 1078)",
  "\"There is no envy except in two cases: a man given wealth who spends it rightly, and a man given wisdom who acts by it and teaches it.\" — Prophet Muhammad ﷺ (Bukhari 73; Muslim 816)",
  "\"Whoever performs Hajj for Allah's sake and avoids obscenity and sin will return as free of sin as the day his mother bore him.\" — Prophet Muhammad ﷺ (Bukhari 1521)",
  "\"Umrah to Umrah is an expiation for what came between them, and the reward of an accepted Hajj is nothing less than Paradise.\" — Prophet Muhammad ﷺ (Bukhari 1773; Muslim 1349)",
  "\"Successful indeed is the one who accepts Islam, is given sufficient provision, and is made content by Allah with what He has given him.\" — Prophet Muhammad ﷺ (Muslim 1054)",
  "\"The believer is like a fresh plant: the wind bends it, yet it recovers. The wicked one is like a rigid pine tree, firm until uprooted all at once.\" — Prophet Muhammad ﷺ (Bukhari 5644; Muslim 2809)",
  "\"Whoever raises two girls with care until they grow up will come with me on the Day of Resurrection like this — joining his fingers together.\" — Prophet Muhammad ﷺ (Muslim 2631)",
  "\"Allah loves sneezing and dislikes yawning.\" — Prophet Muhammad ﷺ (Bukhari 6226)",
  "\"There are three whom Allah will not speak to on the Day of Resurrection: one who lets his garment hang out of pride, reminds others of his gifts, or sells by a false oath.\" — Prophet Muhammad ﷺ (Muslim 106)",
  "\"There is a piece of flesh in the body which, if sound, the whole body is sound, and if corrupt, the whole body is corrupt: it is the heart.\" — Prophet Muhammad ﷺ (Bukhari 52; Muslim 1599)",
  "\"Paradise is surrounded by hardships, and the Fire is surrounded by desires.\" — Prophet Muhammad ﷺ (Bukhari 6487; Muslim 2822)",
  "\"The supplication of a Muslim for his brother in his absence is answered. An angel says: Ameen, and may you have the same.\" — Prophet Muhammad ﷺ (Muslim 2733)",
  "\"When one of you supplicates, let him ask with resolve, and not say: O Allah, give me if You wish — for none can compel Allah.\" — Prophet Muhammad ﷺ (Bukhari 6338)",
  "\"There are three whose supplication is not rejected: the fasting person when he breaks his fast, the just leader, and the one who is wronged.\" — Prophet Muhammad ﷺ (Tirmidhi 3598)",
  "\"When a man has two wives and inclines to one of them, he will come on the Day of Resurrection with a side hanging down.\" — Prophet Muhammad ﷺ (Abu Dawud 2133)",
  "\"Modesty brings nothing except good.\" — Prophet Muhammad ﷺ (Bukhari 6117; Muslim 37)",
  "\"The believer who recites the Qur'an is like a citron, sweet in taste and smell. One who does not recite it is like a date: sweet in taste, with no smell.\" — Prophet Muhammad ﷺ (Bukhari 5059; Muslim 797)",
  "\"Indeed, deeds are judged by how they end.\" — Prophet Muhammad ﷺ (Bukhari 6607)",
  "\"A person will be with those he loves.\" — Prophet Muhammad ﷺ (Bukhari 6168; Muslim 2640)",
  "\"Kindness is not found in anything except that it beautifies it, and it is not removed from anything except that it disgraces it.\" — Prophet Muhammad ﷺ (Muslim 2594)"
];

export function getDailyHadithIndex(date = new Date()) {
  return Math.floor(date.getTime() / 86400000) % tweets.length;
}

export function parseHadith(raw) {
  const quoteMatch = raw.match(/^"([^"]+)"/);
  const citeMatch = raw.match(/\(([^)]+)\)\s*$/);
  return {
    quote: quoteMatch ? quoteMatch[1] : raw,
    citation: citeMatch ? citeMatch[1] : "",
  };
}
